sudo: required
language: generic 
services: 
    - docker

before_install:
    - cd frontend
    - docker build -t valdastrakumas/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true valdastrakumas/docker-react npm run test -- --coverage
